# Generated by Django 2.1 on 2019-01-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pname2', models.CharField(max_length=100)),
                ('hand', models.CharField(max_length=100)),
                ('pos', models.CharField(max_length=100)),
            ],
        ),
    ]
